### ISSUE TITLE
Update verified_tokens.json

### ISSUE THREAD

**Issue by legendbsc** [blockparty-sh/slp-explorer#117]
Please verify CNFT token
19f638953866cae73c81c58e8e947f8b55a0ab76e5566e0b766100d8c98dd9a9
https://t.me/cnftglobal

**Comment by blockparty-sh** [comment]
Please open PR to add this

**Comment by legendbsc** [comment]
Done add PR

Pada tanggal Kam, 11 Mar 2021 03.17, Jt Freeman ***@***.***>
menulis:
