### ISSUE TITLE
Address page doesn't reflect transactions

### ISSUE THREAD

**Issue by jcramer** [blockparty-sh/slp-explorer#30]
This page is blank:
https://simpleledger.info/#address/qqtef4uj6xnp8pkn99tgmxlmpjjz5y447y0vy7ejvn

Address above was involved in this transaction:
https://simpleledger.info/#tx/2618063ea992e84a12ae8e1b1a9aa6942425cf86fe3d840c1bbc4eb84bf3de37

**Comment by blockparty-sh** [comment]
This was resolved, potentially by `reprocess`. I think this _may_ be related to the utxo tracking issue.

**Comment by jcramer** [comment]
Wasn't this related to the address missing the "simpleledger:" part in the url?
