### ISSUE TITLE
Field for Token's "Quantity" is confusing

### ISSUE THREAD

**Issue by jcramer** [blockparty-sh/slp-explorer#31]
I see two issues: 

1. Looking at a token's page shows "Quantity" in the Details section.  Since it is likely that this number may not match the circulating supply it may be best to just remove this field entirely.

<img width="513" alt="image" src="https://user-images.githubusercontent.com/988195/61128003-d3566580-a47e-11e9-8eca-17ff35465e0c.png">

2. Looking at a transaction page, the section for "Token Details" shows "Quantity", which I think should be removed for the same reason as above.  Even more confusing is that the value for quantity is shown as 0 (not sure why this is happening).

<img width="440" alt="image" src="https://user-images.githubusercontent.com/988195/61128158-30eab200-a47f-11e9-940e-795ae0be8d51.png">

**Comment by blockparty-sh** [comment]
These rows have been removed.
