### ISSUE TITLE
Implement NFT1 

### ISSUE THREAD

**Issue by blockparty-sh** [blockparty-sh/slp-explorer#32]
```
tokenDetails.versionType: 129 -- parent nft
tokenDetails.versionType: 65 -- child nft
```

show token type in tokendetails pane

show link to parent on token page / tokendetails pane

add a column on the live feed that shows if it's NFT1 parent or NFT1 child, or just token type 

add a stat that shows number of NFT1 children created

**Comment by jcramer** [comment]
Add to this, Show list of NFT1 children on the parent token page.
