### ISSUE TITLE
About slp icons 

### ISSUE THREAD

**Issue by bregecko** [blockparty-sh/slp-explorer#43]
I am new to github but I did go through the guide. I find it extremely frustrating that I cannot figure out how to get my icon associated with my token. I have spent A LOT of time just trying to figure out how to open a pull request like the directions say to. I also tried opening an issue like the directions say and that supposedly worked. That was over a week ago and still don't have icon with my token. I don't even know how to tell if anything has been done with the issue I opened. When I figure out how to do this myself (associate icon with token) I'm going to either create an app to assist others in this frustrating task (that shouldn't be), or have a video showing people how to do it. Why must it be this freaking difficult? I am about to launch a website and need the tokens to be ready for it! Is there anyone reading this that can help me? Please and thank you for your time.

**Comment by blockparty-sh** [comment]
Hi.

This repo is for the explorer, not the token icons.

You need to open a pull request in this repo: https://github.com/kosinusbch/slp-token-icons
