### ISSUE TITLE
Web app doesn't work consistently with Safari

### ISSUE THREAD

**Issue by jcramer** [blockparty-sh/slp-explorer#68]
In safari browser I get the following error consistently enough to make the site unusable:

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/988195/78558036-ea44a100-77df-11ea-8f3b-0a2712e4e537.png">

```
[Error]  (2)
ErrorEvent {isTrusted: true, message: "Script error.", filename: "", lineno: 0, colno: 0, …}
"#token/9ce9ebb34a1efcbe1649dc6cc9e62a2b2c2c4fb0947d7ea6412adefbc725829c"
	(anonymous function) (bundle.min.js:2:44101)
	(anonymous function) (app.js:4280)
	sentryWrapped (bundle.min.js:2:38771)
```

**Comment by blockparty-sh** [comment]
This is from a cross-origin script, either sha256 or sideshift integration. I added crossorigin="anonymous" which should hopefully irk out a better error.
